workflows:
  android-workflow:
    name: Build Android APK
    environment:
      sdk: 34
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
