workflows:
  android-workflow:
    name: Build Android APK
    environment:
      android:
        image: latest
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk

