workflows:
  android-workflow:
    name: Build Android APK
    environment:
      android: latest
    scripts:
      - name: Make Gradle executable
        script: chmod +x ./gradlew
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
