workflows:
  android-workflow:
    name: Build Android APK
    scripts:
      - name: Make Gradle executable
        script: chmod +x ./gradlew
      - name: Clean project
        script: ./gradlew clean
      - name: Build Debug APK
        script: ./gradlew assembleDebug
      - name: List all APK files
        script: find . -type f -name "*.apk" || true
    artifacts:
      - "**/*.apk"
